/*
 * Copyright 2024 - 2025 Riigi Infosüsteemi Amet
 *
 * Licensed under the EUPL, Version 1.1 or – as soon they will be approved by
 * the European Commission - subsequent versions of the EUPL (the "Licence");
 * You may not use this work except in compliance with the Licence.
 * You may obtain a copy of the Licence at:
 *
 * https://joinup.ec.europa.eu/software/page/eupl
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the Licence is
 * distributed on an "AS IS" basis,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the Licence for the specific language governing permissions and limitations under the Licence.
 */

package ee.openeid.siva.test

// TODO: organize the test data
class TestData {

    static final String TEST_ENV_VALIDATION_WARNING = "This is validation service demo. Use it for testing purposes only"

    static final String MIMETYPE_NOT_FIRST_WARNING = "\"mimetype\" should be the first file in the container"
    static final String MIMETYPE_COMPRESSED_WARNING = "Container \"mimetype\" file must not be compressed"
    static final String MIMETYPE_EXTRA_FIELDS_WARNING = "Container \"mimetype\" file must not contain \"Extra fields\" in its ZIP header"
    static final String MIMETYPE_INVALID_TYPE = "Container should have one of the expected mimetypes: \"application/vnd.etsi.asic-e+zip\", \"application/vnd.etsi.asic-s+zip\""

    static final String VALIDATION_LEVEL_ARCHIVAL_DATA = "ARCHIVAL_DATA"

    static final String MOCK_XADES_SIGNATURE_FILE = "Valid_XAdES_LT_TS.xml"
    static final String MOCK_XADES_SIGNATURE_FILE_NAME = '''VALID_FILENAME+#$!}[]()-_.,;€ˇ~^'äöõü§@.xml'''
    static final String MOCK_XADES_SIGNATURE_ID = "id-3adeffc353d287db270f5fb98bbcda02"
    static final String MOCK_XADES_SIGNATURE_SIGNER = "MÄNNIK,MARI-LIIS,47101010033"
    static final String MOCK_XADES_SIGNATURE_CLAIMED_SIGNING_TIME = "2019-02-05T13:27:22Z"
    static final String MOCK_XADES_SIGNATURE_BEST_SIGNATURE_TIME = "2019-02-05T13:27:24Z"
    static final String MOCK_XADES_DATAFILE_HASH = "RnKZobNWVy8u92sDL4S2j1BUzMT5qTgt6hm90TfAGRo="
    static final String MOCK_XADES_DATAFILE_HASH2 = "47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU="
    static final String MOCK_XADES_DATAFILE_FILENAME = "test.txt"
    static final String MOCK_XADES_DATAFILE_FILENAME2 = "Proov (2).txt"

    static final String VALIDATION_CONCLUSION_PREFIX = "validationReport.validationConclusion."
    static final String VALIDATION_PROCESS_PREFIX = "validationReport.validationProcess."
    static final String VALIDATION_PROCESS_TS_PREFIX = "validationProcess.signatureOrTimestampOrEvidenceRecord.timestamps."
    static final String DIAGNOSTIC_DATA_PREFIX = "validationReport.diagnosticData."

    static final String VALID_INDICATION_VALUE_PASSED = "PASSED"
    static final String VALID_INDICATION_VALUE_FAILED = "FAILED"
    static final String INDETERMINATE= "INDETERMINATE"
    static final String TOTAL_FAILED = "TOTAL-FAILED"
    static final String TOTAL_PASSED = "TOTAL-PASSED"

    // Subindications based on TS 119 102-1 v1.2.1
    static final String SUB_INDICATION_FORMAT_FAILURE = "FORMAT_FAILURE"
    static final String SUB_INDICATION_HASH_FAILURE = "HASH_FAILURE"
    static final String SUB_INDICATION_SIG_CRYPTO_FAILURE = "SIG_CRYPTO_FAILURE"
    static final String SUB_INDICATION_REVOKED = "REVOKED"
    static final String SUB_INDICATION_EXPIRED = "EXPIRED"
    static final String SUB_INDICATION_NOT_YET_VALID = "NOT_YET_VALID"
    static final String SUB_INDICATION_SIG_CONSTRAINTS_FAILURE = "SIG_CONSTRAINTS_FAILURE"
    static final String SUB_INDICATION_CHAIN_CONSTRAINTS_FAILURE = "CHAIN_CONSTRAINTS_FAILURE"
    static final String SUB_INDICATION_CERTIFICATE_CHAIN_GENERAL_FAILURE = "CERTIFICATE_CHAIN_GENERAL_FAILURE"
    static final String SUB_INDICATION_CRYPTO_CONSTRAINTS_FAILURE = "CRYPTO_CONSTRAINTS_FAILURE"
    static final String SUB_INDICATION_POLICY_PROCESSING_ERROR = "POLICY_PROCESSING_ERROR"
    static final String SUB_INDICATION_SIGNATURE_POLICY_NOT_AVAILABLE = "SIGNATURE_POLICY_NOT_AVAILABLE"
    static final String SUB_INDICATION_TIMESTAMP_ORDER_FAILURE = "TIMESTAMP_ORDER_FAILURE"
    static final String SUB_INDICATION_NO_SIGNING_CERTIFICATE_FOUND = "NO_SIGNING_CERTIFICATE_FOUND"
    static final String SUB_INDICATION_NO_CERTIFICATE_CHAIN_FOUND = "NO_CERTIFICATE_CHAIN_FOUND"
    static final String SUB_INDICATION_REVOKED_NO_POE = "REVOKED_NO_POE"
    static final String SUB_INDICATION_REVOKED_CA_NO_POE = "REVOKED_CA_NO_POE "
    static final String SUB_INDICATION_OUT_OF_BOUNDS_NOT_REVOKED = "OUT_OF_BOUNDS_NOT_REVOKED"
    static final String SUB_INDICATION_OUT_OF_BOUNDS_NO_POE = "OUT_OF_BOUNDS_NO_POE"
    static final String SUB_INDICATION_CRYPTO_CONSTRAINTS_FAILURE_NO_POE = "CRYPTO_CONSTRAINTS_FAILURE_NO_POE"
    static final String SUB_INDICATION_NO_POE = "NO_POE"
    static final String SUB_INDICATION_TRY_LATER = "TRY_LATER"
    static final String SUB_INDICATION_SIGNED_DATA_NOT_FOUND = "SIGNED_DATA_NOT_FOUND"

    static final String VALID_SIGNATURE_SCOPE_CONTENT_FULL = "Full document"
    static final String VALID_SIGNATURE_SCOPE_CONTENT_DIGEST = "Digest of the document content"
    static final String VALID_SIGNATURE_SCOPE_CONTENT_2 = "The document byte range: [0, 14153, 52047, 491]"
    static final String SIGNATURE_SCOPE_FULL = "FULL"
    static final String SIGNATURE_SCOPE_DIGEST = "DIGEST"
    static final String VALID_SIGNATURE_SCOPE_VALUE_2 = "PdfByteRangeSignatureScope"


    static final String VALID_VALIDATION_PROCESS_NAMEID_1 = "QUAL_TL_FRESH"
    static final String VALID_VALIDATION_PROCESS_NAMEID_2 = "QUAL_TL_EXP"
    static final String VALID_VALIDATION_PROCESS_NAMEID_3 = "QUAL_TL_VERSION"
    static final String VALID_VALIDATION_PROCESS_NAMEID_4 = "QUAL_TL_WS"
    static final String VALID_VALIDATION_PROCESS_NAMEID_5 = "ADEST_ROBVPIIC"
    static final String VALID_VALIDATION_PROCESS_NAMEID_6 = "LTV_ABSV"
    static final String VALID_VALIDATION_PROCESS_NAMEID_7 = "ARCH_LTVV"
    static final String VALID_VALIDATION_PROCESS_NAMEID_8 = "BBB_FC_IEFF"
    static final String VALID_VALIDATION_PROCESS_NAMEID_9 = "BBB_ICS_ISCI"
    static final String VALID_VALIDATION_PROCESS_NAMEID_10 = "BBB_ICS_ISCS"
    static final String VALID_VALIDATION_PROCESS_NAMEID_11 = "BBB_ICS_ISASCP"
    static final String VALID_VALIDATION_PROCESS_NAMEID_12 = "BBB_ICS_ISACDP"
    static final String VALID_VALIDATION_PROCESS_NAMEID_13 = "BBB_ICS_ICDVV"
    static final String VALID_VALIDATION_PROCESS_NAMEID_14 = "BBB_ICS_AIDNASNE"
    static final String VALID_VALIDATION_PROCESS_NAMEID_15 = "BBB_VCI_ISPK"
    static final String VALID_VALIDATION_PROCESS_NAMEID_16 = "BBB_CV_IRDOF"
    static final String VALID_VALIDATION_PROCESS_NAMEID_17 = "BBB_CV_IRDOI"
    static final String VALID_VALIDATION_PROCESS_NAMEID_18 = "BBB_CV_ISI"
    static final String VALID_VALIDATION_PROCESS_NAMEID_19 = "BBB_SAV_ISQPSTP"
    static final String VALID_VALIDATION_PROCESS_NAMEID_20 = "ASCCM"
    static final String VALID_VALIDATION_PROCESS_NAMEID_21 = "BBB_XCV_CCCBB"
    static final String VALID_VALIDATION_PROCESS_NAMEID_22 = "XCV_TSL_ETIP"
    static final String VALID_VALIDATION_PROCESS_NAMEID_23 = "XCV_TSL_ESP"
    static final String VALID_VALIDATION_PROCESS_NAMEID_24 = "BBB_XCV_SUB"
    static final String VALID_VALIDATION_PROCESS_NAMEID_25 = "BBB_XCV_SUB_ANS"
    static final String VALID_VALIDATION_PROCESS_NAMEID_26 = "BBB_XCV_ICSI"
    static final String VALID_VALIDATION_PROCESS_NAMEID_27 = "BBB_SAV_TSP_IMIVC"
    static final String VALID_VALIDATION_PROCESS_NAMEID_28 = "BBB_XCV_ISCGKU"
    static final String VALID_VALIDATION_PROCESS_NAMEID_29 = "BBB_XCV_ISCR"
    static final String VALID_VALIDATION_PROCESS_NAMEID_30 = "BBB_XCV_ISCOH"
    static final String VALID_VALIDATION_PROCESS_NAMEID_31 = "BBB_XCV_ICTIVRSC"
    static final String VALID_VALIDATION_PROCESS_NAMEID_32 = "BBB_XCV_ICTIVRSC_ANS"
    static final String VALID_VALIDATION_PROCESS_NAMEID_33 = "BBB_XCV_IRDPFC"
    static final String VALID_VALIDATION_PROCESS_NAMEID_34 = "QUAL_IS_ADES"
    static final String VALID_VALIDATION_PROCESS_NAMEID_35 = "QUAL_IS_ADES_INV"
    static final String VALID_VALIDATION_PROCESS_NAMEID_36 = "QUAL_TRUSTED_CERT_PATH"
    static final String VALID_VALIDATION_PROCESS_NAMEID_37 = "QUAL_TL_SERV_CONS"
    static final String VALID_VALIDATION_PROCESS_NAMEID_38 = "QUAL_TL_CERT_CONS"
    static final String VALID_VALIDATION_PROCESS_NAMEID_39 = "QUAL_QC_AT_ST"
    static final String VALID_VALIDATION_PROCESS_NAMEID_40 = "QUAL_FOR_SIGN_AT_ST"
    static final String VALID_VALIDATION_PROCESS_NAMEID_41 = "QUAL_QC_AT_CC"
    static final String VALID_VALIDATION_PROCESS_NAMEID_42 = "QUAL_QSCD_AT_ST"
    static final String VALID_VALIDATION_PROCESS_NAMEID_43 = "BBB_XCV_CMDCIQC"
    static final String VALID_VALIDATION_PROCESS_NAMEID_44 = "BBB_SAV_TSP_IMIDF"
    static final String VALID_VALIDATION_PROCESS_NAMEID_45 = "BBB_RFC_NUP"
    static final String VALID_VALIDATION_PROCESS_NAMEID_46 = "BBB_RFC_NUP_ANS"
    static final String VALID_VALIDATION_PROCESS_NAMEID_47 = "BBB_RFC_IRIF"
    static final String VALID_VALIDATION_PROCESS_NAMEID_48 = "QUAL_TRUSTED_LIST_ACCEPT"
    static final String VALID_VALIDATION_PROCESS_NAMEID_49 = "ADEST_ROTVPIIC"
    static final String VALID_VALIDATION_PROCESS_NAMEID_50 = "ADEST_RORPIIC"
    static final String VALID_VALIDATION_PROCESS_NAMEID_51 = "TSV_ASTPTCT"
    static final String VALID_VALIDATION_PROCESS_NAMEID_52 = "ADEST_ISTPTDABST"
    static final String VALID_VALIDATION_PROCESS_NAMEID_53 = "QUAL_UNIQUE_CERT"
    static final String VALID_VALIDATION_PROCESS_NAMEID_54 = "ATCCM"
    static final String VALID_VALIDATION_PROCESS_NAMEID_55 = "ARCCM"
    static final String VALID_VALIDATION_PROCESS_NAMEID_56 = "BBB_XCV_IRDC"
    static final String VALID_VALIDATION_PROCESS_NAMEID_57 = "BBB_XCV_IARDPFC"
    static final String VALID_VALIDATION_PROCESS_NAMEID_59 = "BBB_SAV_ISQPMDOSPP"
    static final String VALID_VALIDATION_PROCESS_NAMEID_60 = "BBB_SAV_ISSV"

    static final String VALID_VALIDATION_PROCESS_VALUE_1 = "Is the trusted list fresh ?"
    static final String VALID_VALIDATION_PROCESS_VALUE_2 = "Is the trusted list not expired ?"
    static final String VALID_VALIDATION_PROCESS_VALUE_3 = "Is the trusted list has the expected version ?"
    static final String VALID_VALIDATION_PROCESS_VALUE_4 = "Is the trusted list well signed ?"
    static final String VALID_VALIDATION_PROCESS_VALUE_5 = "Is the result of the Basic Validation Process conclusive?"
    static final String VALID_VALIDATION_PROCESS_VALUE_6 = "Is the result of the Basic Validation Process acceptable?"
    static final String VALID_VALIDATION_PROCESS_VALUE_7 = "Is the result of the LTV validation process acceptable?"
    static final String VALID_VALIDATION_PROCESS_VALUE_8 = "Is the expected format found?"
    static final String VALID_VALIDATION_PROCESS_VALUE_9 = "Is there an identified candidate for the signing certificate?"
    static final String VALID_VALIDATION_PROCESS_VALUE_10 = "Is the signing certificate signed?"
    static final String VALID_VALIDATION_PROCESS_VALUE_11 = "Is the signed attribute: 'signing-certificate' present?"
    static final String VALID_VALIDATION_PROCESS_VALUE_12 = "Is the signed attribute: 'cert-digest' of the certificate present?"
    static final String VALID_VALIDATION_PROCESS_VALUE_13 = "Is the certificate's digest value valid?"
    static final String VALID_VALIDATION_PROCESS_VALUE_14 = "Are the issuer distinguished name and the serial number equal?"
    static final String VALID_VALIDATION_PROCESS_VALUE_15 = "Is the signature policy known?"
    static final String VALID_VALIDATION_PROCESS_VALUE_16 = "Has the reference data object been found?"
    static final String VALID_VALIDATION_PROCESS_VALUE_17 = "Is the reference data object intact?"
    static final String VALID_VALIDATION_PROCESS_VALUE_18 = "Is the signature intact?"
    static final String VALID_VALIDATION_PROCESS_VALUE_19 = "Is the signed qualifying property: 'signing-time' present?"
    static final String VALID_VALIDATION_PROCESS_VALUE_20 = "Are signature cryptographic constraints met?"
    static final String VALID_VALIDATION_PROCESS_VALUE_21 = "Can the certificate chain be built till a trust anchor?"
    static final String VALID_VALIDATION_PROCESS_VALUE_22 = "Has a trust service with an expected type identifier been found?"
    static final String VALID_VALIDATION_PROCESS_VALUE_23 = "Is the expected trust service status present ?"
    static final String VALID_VALIDATION_PROCESS_VALUE_24 = "Is the certificate validation conclusive?"
    static final String VALID_VALIDATION_PROCESS_VALUE_25 = "The certificate validation is not concluant!"
    static final String VALID_VALIDATION_PROCESS_VALUE_26 = "Is the certificate's signature intact?"
    static final String VALID_VALIDATION_PROCESS_VALUE_27 = "Is message imprint verification conclusive?"
    static final String VALID_VALIDATION_PROCESS_VALUE_28 = "Has the signer's certificate given key-usage?"
    static final String VALID_VALIDATION_PROCESS_VALUE_29 = "Is the certificate not revoked?"
    static final String VALID_VALIDATION_PROCESS_VALUE_30 = "Is the certificate on hold?"
    static final String VALID_VALIDATION_PROCESS_VALUE_31 = "Is the current time in the validity range of the signer's certificate?"
    static final String VALID_VALIDATION_PROCESS_VALUE_32 = "Certificate meta-data constraints: Is the signer's certificate qualified?"
    static final String VALID_VALIDATION_PROCESS_VALUE_33 = "Is the revocation data present for the certificate?"
    static final String VALID_VALIDATION_PROCESS_VALUE_34 = "Is the signature/seal an acceptable AdES (ETSI EN 319 102-1) ?"
    static final String VALID_VALIDATION_PROCESS_VALUE_35 = "The signature/seal is not a valid AdES digital signature!"
    static final String VALID_VALIDATION_PROCESS_VALUE_36 = "Is the certificate path trusted?"
    static final String VALID_VALIDATION_PROCESS_VALUE_37 = "Are trust services consistent ?"
    static final String VALID_VALIDATION_PROCESS_VALUE_38 = "Is the certificate consistent with the trusted list ?"
    static final String VALID_VALIDATION_PROCESS_VALUE_39 = "Is the certificate qualifed at signing time?"
    static final String VALID_VALIDATION_PROCESS_VALUE_40 = "Is the certificate for eSig at signing time?"
    static final String VALID_VALIDATION_PROCESS_VALUE_41 = "Is the certificate qualifed at issuance time?"
    static final String VALID_VALIDATION_PROCESS_VALUE_42 = "Is the signature/seal created by a QSCD?"
    static final String VALID_VALIDATION_PROCESS_VALUE_43 = "Is message imprint data found?"
    static final String VALID_VALIDATION_PROCESS_VALUE_44 = "Is there a Next Update defined for the revocation data?"
    static final String VALID_VALIDATION_PROCESS_VALUE_45 = "There is no Next Update defined for the revocation data!"
    static final String VALID_VALIDATION_PROCESS_VALUE_46 = "Is the revocation information fresh for the certificate?"
    static final String VALID_VALIDATION_PROCESS_VALUE_47 = "Is the trusted list acceptable?"
    static final String VALID_VALIDATION_PROCESS_VALUE_48 = "Is the result of the timestamps validation process conclusive?"
    static final String VALID_VALIDATION_PROCESS_VALUE_49 = "Is the result of the revocation data validation process acceptable?"
    static final String VALID_VALIDATION_PROCESS_VALUE_50 = "Are the timestamps in the right order?"
    static final String VALID_VALIDATION_PROCESS_VALUE_51 = "Is the signing-time plus the timestamp delay after best-signature-time?"
    static final String VALID_VALIDATION_PROCESS_VALUE_52 = "Is the certificate unique ?"
    static final String VALID_VALIDATION_PROCESS_VALUE_53 = "Are timestamp cryptographic constraints met?"
    static final String VALID_VALIDATION_PROCESS_VALUE_54 = "Are revocation cryptographic constraints met?"
    static final String VALID_VALIDATION_PROCESS_VALUE_55 = "Is timestamp's signature intact?"
    static final String VALID_VALIDATION_PROCESS_VALUE_56 = "Is revocation's signature intact?"
    static final String VALID_VALIDATION_PROCESS_VALUE_57 = "Is the revocation data consistent?"
    static final String VALID_VALIDATION_PROCESS_VALUE_58 = "Is an acceptable revocation data present for the certificate?"
    static final String VALID_VALIDATION_PROCESS_VALUE_59 = "Is the signed qualifying property: 'message-digest' or 'SignedProperties' present?"
    static final String VALID_VALIDATION_PROCESS_VALUE_60 = "Is the structure of the signature valid?"

    static final String VALID_VALIDATION_PROCESS_ERROR_VALUE_1 = "The result of the Basic validation process is not conclusive!"
    static final String VALID_VALIDATION_PROCESS_ERROR_VALUE_2 = "The expected format is not found!"
    static final String VALID_VALIDATION_PROCESS_ERROR_VALUE_3 = "The result of the Basic validation process is not acceptable to continue the process!"
    static final String VALID_VALIDATION_PROCESS_ERROR_VALUE_4 = "The expected format is not found!"
    static final String VALID_VALIDATION_PROCESS_ERROR_VALUE_5 = "No acceptable revocation data for the certificate!"
    static final String VALID_VALIDATION_PROCESS_ERROR_VALUE_6 = "The expected format is not found!"
    static final String VALID_VALIDATION_PROCESS_ERROR_VALUE_7 = "The certificate is not qualified!"
    static final String VALID_VALIDATION_PROCESS_ERROR_VALUE_8 = "No revocation data for the certificate"
    static final String VALID_VALIDATION_PROCESS_ERROR_VALUE_9 = "The signature is not intact!"
    static final String VALID_VALIDATION_PROCESS_ERROR_VALUE_10 = "The current time is not in the validity range of the signer's certificate!"
    static final String VALID_VALIDATION_PROCESS_ERROR_VALUE_11 = "The certificate is not related to a granted status at time-stamp generation time!"
    static final String CERT_VALIDATION_NOT_CONCLUSIVE = "The certificate validation is not conclusive!"
    static final String CERT_NOT_GRANTED = "The certificate is not related to a granted status!"
    static final String TS_PROCESS_NOT_CONCLUSIVE = "The result of the timestamps validation process is not conclusive!"
    static final String TS_MESSAGE_NOT_INTACT = "The time-stamp message imprint is not intact!"
    static final String TS_NOT_TRUSTED = "The certificate chain for time-stamp is not trusted, it does not contain a trust anchor."
    static final String REFERENCE_DATA_NOT_INTACT = "The reference data object is not intact!"
    static final String REFERENCE_DATA_NOT_FOUND = "The reference data object has not been found!"
    static final String CERTIFICATE_DO_NOT_MATCH_TRUST_SERVICE = "The trusted certificate doesn't match the trust service"
    static final String CERT_NOT_RELATED_TO_QUALIFIED_TRUST_SERVICE = "The certificate is not related to a qualified certificate issuing trust service with valid status!"
    static final String PAST_SIG_VALIDATION_NOT_CONCLUSIVE = "The past signature validation is not conclusive!"
    static final String SIG_CREATED_WITH_EXP_CERT = "Signature has been created with expired certificate"
    static final String SIG_UNEXPECTED_FORMAT = "The signature does not correspond to the expected format(s)!"
    static final String SIG_NOT_TRUSTED = "The certificate chain for signature is not trusted, it does not contain a trust anchor."
    static final String SIG_NO_CANDIDATE = "There is no candidate for the signing certificate!"
    static final String SIG_INVALID_TS = "Signature has an invalid timestamp"
    static final String CERT_PATH_NOT_TRUSTED = "Unable to build a certificate chain up to a trusted list!"
    static final String REVOCATION_NOT_FRESH = "The revocation information is not considered as 'fresh'."
    static final String REVOCATION_NOT_TRUSTED = "The certificate chain for revocation data is not trusted, it does not contain a trust anchor."
    static final String REVOCATION_UNKNOWN = "The revocation status is unknown (Unknown response from OCSP)!"
    static final String REVOCATION_NOT_FOUND = "No revocation data found for the certificate!"
    static final String REVOCATION_NOT_CONSISTENT = "The revocation data is not consistent!"
    static final String ALL_FILES_NOT_SIGNED = "Not all files are signed!"
    static final String NOT_EXPECTED_KEY_USAGE = "The signing-certificate of signature does not have an expected key-usage!"
    static final String SIG_QUALIFYING_PROPERTY_MISSING = "The signed qualifying property: neither 'message-digest' nor 'SignedProperties' is present!"

    static final String NOT_GRANTED_CONTAINER_WARNING = "Found a timestamp token not related to granted status. If not yet covered with a fresh timestamp token, this container might become invalid in the future."

}
